baseURL = "https://updates.vfxwatch.com"
languageCode = "en-us"
title = "Updates"
contentDir = "Content"
paginate = 5
theme = "poole"

[author]
  name = 'bijumon'
  email = 'bj@you.got.mail'

[params]
  tagline = "I dont think I've become old. Just more aware of where the next lavatory is - Terry Pratchett, The Last Hero"

[permalinks]
  posts = '/:year/:month/:title/'
