baseURL = "https://updates.vfxwatch.com"
languageCode = "en-us"
title = "Updates"
contentDir = "Content"
paginate = 5
theme = "poole"

[author]
  name = 'bijumon'
  email = 'bj@you.got.mail'

[params]
  tagline = "Time and I have quarrelled. All hours are midnight now. I had a clock and a watch, but I destroyed them both. I could not bear the way they mocked me --  Susanna Clarke, Jonathan Strange & Mr Norrell"

[permalinks]
  updates = '/:year/:month/:title/'

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"