baseURL = "https://updates.vfxwatch.com"
languageCode = "en-us"
title = "Updates"
contentDir = "Content"
paginate = 5
pluralizelisttitles = false

[author]
  name = 'bijumon'
  email = 'bj@you.got.mail'

[params]
  tagline = ""

[permalinks]
  updates = '/:year/:month/:title/'

[outputs]
    page = ["HTML"]
    home = ["HTML", "RSS"]
    section = ["HTML"]
    taxonomyTerm = ["HTML"]
    taxonomy = ["HTML"]

[outputFormats]
  [outputFormats.RSS]
    mediatype = "application/rss"
    baseName = "rss"
