description = "hugo theme for updates blog"
features    = []
homepage    = "https://github.com/bijumon/updates-vlog/"
license     = "BSD"
licenselink = ""
min_version = "0.1"
name        = "bklogs"
tags        = ["blog", "personal"]

[author]
homepage = "https://updates.vfxwatch.com"
name     = "bijumon"
